import { Injectable } from "@nestjs/common"
import { pdfBuyerInterface } from "./interface/pdf.interface"
import * as PDFDocument from "pdfkit"
import { PdfService } from "../services/utils/pdf/pdf.service"

@Injectable()
export class BuyerService {
  constructor(private readonly pdfService: PdfService) {}

  async generateBuyerPdf(data: pdfBuyerInterface): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: "A4",
          margin: 50,
          info: {
            Title: `Buyer Profile - ${data.profile.fullName}`,
            Author: "Skicom Management System",
            Subject: "Skicom Buyer Profile Document",
            Creator: "Skicom Profile Service"
          }
        })

        doc.fillColor("#FFFFFF").rect(0, 0, doc.page.width, doc.page.height).fill()

        const buffers: Buffer[] = []

        doc.on("data", (chunk) => buffers.push(chunk))
        doc.on("end", () => resolve(Buffer.concat(buffers)))
        doc.on("error", (err) => reject(err))

        this.generateBuyPdfContent(doc, data)
        doc.end()
      } catch (error) {
        console.error("PDF generation error:", error)
        reject(error)
      }
    })
  }

  async generateBuyPdfContent(doc: PDFKit.PDFDocument, data: pdfBuyerInterface) {
    // Set default font
    doc.font("Helvetica")

    // Header
    doc.fillColor("#1DA1F2").opacity(0.1).roundedRect(50, 50, 495, 60, 10).fill()
    doc.opacity(1).fontSize(20).fillColor("#1DA1F2").text(`Buyer's Profile - ${data.profile.fullName}`, 50, 60, {
      align: "center"
    })

    let yPos = 130

    // ====================
    // PROFILE OVERVIEW
    // ====================
    this.pdfService.addSectionHeader(doc, "Profile Overview", yPos)
    yPos += 20
    yPos = this.pdfService.addTwoColumnPair(doc, "Full Name:", data.profile.fullName || "-", "Email Address:", data.profile.email || "-", yPos)
    yPos = this.pdfService.addTwoColumnPair(
      doc,
      "Phone Number:",
      data.profile.phoneNumber?.toString() || "-",
      "Date Joined:",
      data.profile.dateJoined?.toLocaleDateString() || "-",
      yPos
    )
    yPos = this.pdfService.addTwoColumnPair(
      doc,
      "Status:",
      data.profile.status || "-",
      "Last Activity:",
      data.profile.lastActivity?.toLocaleDateString() || "-",
      yPos
    )

    // Check for page break needed
    yPos = this.pdfService.checkPageBreak(doc, yPos, 100)

    // ====================
    // ORDER HISTORY
    // ====================
    yPos += 20
    this.pdfService.addSectionHeader(doc, "Order History", yPos)
    yPos += 20

    // Table Header
    doc.fontSize(10).fillColor("#000000")
    this.pdfService.createTableHeader(doc, yPos, [
      { text: "Order ID", width: 120, x: 70 },
      { text: "Date Ordered", width: 100, x: 200 },
      { text: "Vendor", width: 100, x: 310 },
      { text: "Amount", width: 80, x: 420 },
      { text: "Status", width: 60, x: 510 }
    ])
    yPos += 15

    // Table Rows
    const orders = data.orders || []
    orders.forEach((order, index) => {
      if (yPos > doc.page.height - 50) {
        doc.addPage()
        yPos = 50
        this.pdfService.createTableHeader(doc, yPos, [
          { text: "Order ID", width: 120, x: 70 },
          { text: "Date Ordered", width: 100, x: 200 },
          { text: "Vendor", width: 100, x: 310 },
          { text: "Amount", width: 80, x: 420 },
          { text: "Status", width: 60, x: 510 }
        ])
        yPos += 15
      }

      doc.fontSize(8).fillColor("#333333")
      doc.text(order.id || "-", 70, yPos, { width: 120, ellipsis: true })
      doc.text(order.dateOrdered?.toLocaleDateString() || "-", 200, yPos, { width: 100 })
      doc.text(order.vendorName || "-", 310, yPos, { width: 100, ellipsis: true })
      doc.text(`$${order.totalAmount?.toFixed(2) || "0.00"}`, 420, yPos, { width: 80 })
      doc.text(order.status || "-", 510, yPos, { width: 60 })

      if (index % 2 === 0) {
        doc
          .opacity(0.05)
          .fillColor("#1DA1F2")
          .rect(50, yPos - 5, 495, 15)
          .fill()
          .opacity(1)
      }

      yPos += 15
    })

    // Footer
    this.pdfService.addFooter(doc, "Generated by Skicom Management System")
  }
}
